# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{any-spec}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gough"]
  s.date = %q{2010-10-09}
  s.description = %q{AnySpec is a framework for writing executable language specifications and automated black-box functional tests for programming languages.}
  s.email = %q{aaron@aarongough.com}
  s.executables = ["any-spec", "any-spec"]
  s.extra_rdoc_files = [
    "MIT-LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "any-spec.gemspec",
     "bin/any-spec",
     "lib/any-spec.rb",
     "lib/any-spec/assertions.rb",
     "lib/any-spec/test-case.rb",
     "lib/any-spec/test-runner.rb",
     "test/fixtures/example_test_specification.yml",
     "test/fixtures/test_cases/empty.blah",
     "test/fixtures/test_cases/error.rb",
     "test/fixtures/test_cases/failing.rb",
     "test/fixtures/test_cases/incorrect.blah",
     "test/fixtures/test_cases/test1.rb",
     "test/fixtures/test_cases/test2.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/assertions_test.rb",
     "test/unit/test_case_test.rb",
     "test/unit/test_runner_test.rb"
  ]
  s.homepage = %q{http://github.com/aarongough/any-spec}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A framework for writing executable language specifications}
  s.test_files = [
    "test/fixtures/test_cases/error.rb",
     "test/fixtures/test_cases/failing.rb",
     "test/fixtures/test_cases/test1.rb",
     "test/fixtures/test_cases/test2.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/assertions_test.rb",
     "test/unit/test_case_test.rb",
     "test/unit/test_runner_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

